# This file is part of pyopc.
#
# pyopc is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# pyopc is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
# Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with pyopc.  If not, see
# <http://www.gnu.org/licenses/>.
#
# $Id$
#
################################################## 
# OpcXmlDaSrv_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from OpcXmlDaSrv_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class OpcXmlDaSrvLocator:
    OpcXmlDaSrvSoap_address = ""
    def getOpcXmlDaSrvSoapAddress(self):
        return OpcXmlDaSrvLocator.OpcXmlDaSrvSoap_address
    def getOpcXmlDaSrvSoap(self, url=None, **kw):
        return OpcXmlDaSrvSoapSOAP(url or OpcXmlDaSrvLocator.OpcXmlDaSrvSoap_address, **kw)

# Methods
class OpcXmlDaSrvSoapSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: GetProperties
    def GetProperties(self, request):
        if isinstance(request, GetPropertiesSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/GetProperties", **kw)
        # no output wsaction
        response = self.binding.Receive(GetPropertiesSoapOut.typecode)
        return response

    # op: Subscribe
    def Subscribe(self, request):
        if isinstance(request, SubscribeSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/Subscribe", **kw)
        # no output wsaction
        response = self.binding.Receive(SubscribeSoapOut.typecode)
        return response

    # op: SubscriptionPolledRefresh
    def SubscriptionPolledRefresh(self, request):
        if isinstance(request, SubscriptionPolledRefreshSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionPolledRefresh", **kw)
        # no output wsaction
        response = self.binding.Receive(SubscriptionPolledRefreshSoapOut.typecode)
        return response

    # op: SubscriptionCancel
    def SubscriptionCancel(self, request):
        if isinstance(request, SubscriptionCancelSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionCancel", **kw)
        # no output wsaction
        response = self.binding.Receive(SubscriptionCancelSoapOut.typecode)
        return response

    # op: GetStatus
    def GetStatus(self, request):
        if isinstance(request, GetStatusSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/GetStatus", **kw)
        # no output wsaction
        response = self.binding.Receive(GetStatusSoapOut.typecode)
        return response

    # op: Browse
    def Browse(self, request):
        if isinstance(request, BrowseSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/Browse", **kw)
        # no output wsaction
        response = self.binding.Receive(BrowseSoapOut.typecode)
        return response

    # op: Read
    def Read(self, request):
        if isinstance(request, ReadSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/Read", **kw)
        # no output wsaction
        response = self.binding.Receive(ReadSoapOut.typecode)
        return response

    # op: Write
    def Write(self, request):
        if isinstance(request, WriteSoapIn) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://opcfoundation.org/webservices/XMLDA/1.0/Write", **kw)
        # no output wsaction
        response = self.binding.Receive(WriteSoapOut.typecode)
        return response

GetPropertiesSoapIn = ns0.GetProperties_Dec().pyclass

GetPropertiesSoapOut = ns0.GetPropertiesResponse_Dec().pyclass

SubscribeSoapIn = ns0.Subscribe_Dec().pyclass

SubscribeSoapOut = ns0.SubscribeResponse_Dec().pyclass

SubscriptionPolledRefreshSoapIn = ns0.SubscriptionPolledRefresh_Dec().pyclass

SubscriptionPolledRefreshSoapOut = ns0.SubscriptionPolledRefreshResponse_Dec().pyclass

SubscriptionCancelSoapIn = ns0.SubscriptionCancel_Dec().pyclass

SubscriptionCancelSoapOut = ns0.SubscriptionCancelResponse_Dec().pyclass

GetStatusSoapIn = ns0.GetStatus_Dec().pyclass

GetStatusSoapOut = ns0.GetStatusResponse_Dec().pyclass

BrowseSoapIn = ns0.Browse_Dec().pyclass

BrowseSoapOut = ns0.BrowseResponse_Dec().pyclass

ReadSoapIn = ns0.Read_Dec().pyclass

ReadSoapOut = ns0.ReadResponse_Dec().pyclass

WriteSoapIn = ns0.Write_Dec().pyclass

WriteSoapOut = ns0.WriteResponse_Dec().pyclass
